title: doc
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://abilpraju-aot.github.io/documentation

aux_links:
  Template Repository: https://abilpraju-aot.github.io/documentation
